"use client";
import "./globals.css";

import { Inter } from "next/font/google";
import { Provider } from "react-redux";
import store from "./store";
import UserForm from "./sign-in/page";
import Dashboard from "./dashboard/page";

const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  return (
    <Provider store={store}>
      <body className={inter.className}>{children}</body>
    </Provider>
  );
}
